### ISSUE TITLE
I find this inappropriate.

### ISSUE THREAD

**Issue by adunkman** [letsgetrandy/DICSS#11]
I get that this is a joke and all, but it seems inappropriate for this community. 

You might reconsider how this is received and the statement it is making.

**Comment by letsgetrandy** [comment]
Thanks for your opinion.  That's the beauty of free speech, isn't it?  I can make jokes you don't like, and you can express your dislike for them. Neither of us has to die as a result, and the world keeps on turning.

Best wishes.

**Comment by OscarGodson** [comment]
This repo can die tho under GitHub terms:

> containing Content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party's intellectual property or these Terms of Service.

Free speech only applies to being prosecuted, not for private companies and the content you make on them. The repo is indeed objectionable and it's offensive. Dick jokes are, like, super funny and all that, but you might wanna be careful that your entire account, which seems to have your work on it all the way back to 2012 doesnt get deleted just because you love dick jokes so much.

**Comment by letsgetrandy** [comment]
Selective quoting is weak.  Here's the whole thing:

> We may, but have no obligation to, remove Content and Accounts containing Content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party's intellectual property or these Terms of Service.

If Github chooses to remove it, that's on them. But with [the attention this is drawing](http://www.businessinsider.com/joke-github-dicss-project-goes-nuts-2015-3), that might have unexpected consequences as well.

**Comment by OscarGodson** [comment]
Dude, I just don't get why you want to inject toxicness into a community. Look at the flame wars going on in your github tickets. Whether you find it super hilarious to make dick jokes or not it's making people argue and becoming enraged. And you're promoting and facilitating that. It's fucked and its damaging and I don't get the appeal of doing it.

**Comment by letsgetrandy** [comment]
And just to be clear... while this is certainly admittedly laced with humor (which some people may deem to be crude), this is a _functioning_ repo, with code that does exactly what the documentation says it does.  It was never intended to offend, but I think now that it has reached the fever pitch that it has, I am personally _more inclined_ to leave it here rather than delete it, because of the dialog it has spawned.

Whether or not I agree with everything that's been said, I think it's good for sensitive topics to get out into the open. However, I would like to make one small plea to everyone who's arguing here, that if you put that same amount of passion into feeding the hungry, clothing the homeless, or ending violence and rape in communities where _real_ violence is actually happening, maybe the world would be a better place.

**Comment by neppermint** [comment]
> if you put that same amount of passion into feeding the hungry, clothing the homeless, or ending violence and rape in communities where real violence is actually happening, maybe the world would be a better place.

That involves putting in effort beyond Slacktivism.

**Comment by jpdevries** [comment]
My Father suffered his entire life from a botched circumcision. In his early 50s, his penis was amputated in an attempt to stop the aggressive cancer that ultimately took his life just a few years later. Had he not been circumcised he would probably still be healthy and well. Serious and painful health complications or death happens as a result of every 1/250,000 circumcisions performed in the United States.

> Circum-Sizer (calculate the circumference of a rounded element in CSS)

Naming your tools after dick jokes or mutilating practices likes circumcision is something you are free to do but you may want to re-consider. _The word itself is painful to me in a way that I can only imagine "rape" would be to a rape victim_.

``` js
// dicss.js -- directly injected css
  if ( ({})<=8 ) {
    // yeah, you get it...
  }
```

Also, really man? :-1: 

We can't get passed the first 10 lines of your actual source code without an offensive superfluous conditional that does nothing so please tell us, why should any of us take you serious as an actual programmer?

**Comment by thewarpaint** [comment]
I'm just going to leave this here: http://www.goodreads.com/quotes/706825-it-s-now-very-common-to-hear-people-say-i-m-rather
